# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_files/create_quiz.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CreateQuizDialog(object):
    def setupUi(self, CreateQuizDialog):
        CreateQuizDialog.setObjectName("CreateQuizDialog")
        CreateQuizDialog.resize(500, 400)
        self.verticalLayout = QtWidgets.QVBoxLayout(CreateQuizDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_title = QtWidgets.QLabel(CreateQuizDialog)
        self.label_title.setObjectName("label_title")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_title)
        self.lineEdit_title = QtWidgets.QLineEdit(CreateQuizDialog)
        self.lineEdit_title.setObjectName("lineEdit_title")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_title)
        self.label_question = QtWidgets.QLabel(CreateQuizDialog)
        self.label_question.setObjectName("label_question")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_question)
        self.lineEdit_question = QtWidgets.QLineEdit(CreateQuizDialog)
        self.lineEdit_question.setObjectName("lineEdit_question")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_question)
        self.label_type = QtWidgets.QLabel(CreateQuizDialog)
        self.label_type.setObjectName("label_type")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_type)
        self.comboBox_type = QtWidgets.QComboBox(CreateQuizDialog)
        self.comboBox_type.setObjectName("comboBox_type")
        self.comboBox_type.addItem("")
        self.comboBox_type.addItem("")
        self.comboBox_type.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBox_type)
        self.label_options = QtWidgets.QLabel(CreateQuizDialog)
        self.label_options.setObjectName("label_options")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_options)
        self.textEdit_options = QtWidgets.QTextEdit(CreateQuizDialog)
        self.textEdit_options.setObjectName("textEdit_options")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.textEdit_options)
        self.label_correct_answer = QtWidgets.QLabel(CreateQuizDialog)
        self.label_correct_answer.setObjectName("label_correct_answer")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_correct_answer)
        self.lineEdit_correct_answer = QtWidgets.QLineEdit(CreateQuizDialog)
        self.lineEdit_correct_answer.setObjectName("lineEdit_correct_answer")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_correct_answer)
        self.verticalLayout.addLayout(self.formLayout)
        self.btn_add_question = QtWidgets.QPushButton(CreateQuizDialog)
        self.btn_add_question.setObjectName("btn_add_question")
        self.verticalLayout.addWidget(self.btn_add_question)
        self.btn_save_quiz = QtWidgets.QPushButton(CreateQuizDialog)
        self.btn_save_quiz.setObjectName("btn_save_quiz")
        self.verticalLayout.addWidget(self.btn_save_quiz)

        self.retranslateUi(CreateQuizDialog)
        QtCore.QMetaObject.connectSlotsByName(CreateQuizDialog)

    def retranslateUi(self, CreateQuizDialog):
        _translate = QtCore.QCoreApplication.translate
        CreateQuizDialog.setWindowTitle(_translate("CreateQuizDialog", "Create Quiz"))
        self.label_title.setText(_translate("CreateQuizDialog", "Quiz Title:"))
        self.label_question.setText(_translate("CreateQuizDialog", "Question:"))
        self.label_type.setText(_translate("CreateQuizDialog", "Question Type:"))
        self.comboBox_type.setItemText(0, _translate("CreateQuizDialog", "Single Choice"))
        self.comboBox_type.setItemText(1, _translate("CreateQuizDialog", "Multiple Choice"))
        self.comboBox_type.setItemText(2, _translate("CreateQuizDialog", "Text Answer"))
        self.label_options.setText(_translate("CreateQuizDialog", "Options (comma-separated):"))
        self.label_correct_answer.setText(_translate("CreateQuizDialog", "Correct Answer:"))
        self.btn_add_question.setText(_translate("CreateQuizDialog", "Add Question"))
        self.btn_save_quiz.setText(_translate("CreateQuizDialog", "Save Quiz"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CreateQuizDialog = QtWidgets.QDialog()
    ui = Ui_CreateQuizDialog()
    ui.setupUi(CreateQuizDialog)
    CreateQuizDialog.show()
    sys.exit(app.exec_())
