# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_files/main_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 300)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_create_quiz = QtWidgets.QPushButton(self.centralwidget)
        self.btn_create_quiz.setObjectName("btn_create_quiz")
        self.verticalLayout.addWidget(self.btn_create_quiz)
        self.btn_take_quiz = QtWidgets.QPushButton(self.centralwidget)
        self.btn_take_quiz.setObjectName("btn_take_quiz")
        self.verticalLayout.addWidget(self.btn_take_quiz)
        self.btn_view_stats = QtWidgets.QPushButton(self.centralwidget)
        self.btn_view_stats.setObjectName("btn_view_stats")
        self.verticalLayout.addWidget(self.btn_view_stats)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Quiz Application"))
        self.btn_create_quiz.setText(_translate("MainWindow", "Create Quiz"))
        self.btn_take_quiz.setText(_translate("MainWindow", "Take Quiz"))
        self.btn_view_stats.setText(_translate("MainWindow", "View Statistics"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
