# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_files/take_quiz.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TakeQuizDialog(object):
    def setupUi(self, TakeQuizDialog):
        TakeQuizDialog.setObjectName("TakeQuizDialog")
        TakeQuizDialog.resize(500, 400)
        self.verticalLayout = QtWidgets.QVBoxLayout(TakeQuizDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_question = QtWidgets.QLabel(TakeQuizDialog)
        self.label_question.setObjectName("label_question")
        self.verticalLayout.addWidget(self.label_question)
        self.radioButton_option1 = QtWidgets.QRadioButton(TakeQuizDialog)
        self.radioButton_option1.setObjectName("radioButton_option1")
        self.verticalLayout.addWidget(self.radioButton_option1)
        self.radioButton_option2 = QtWidgets.QRadioButton(TakeQuizDialog)
        self.radioButton_option2.setObjectName("radioButton_option2")
        self.verticalLayout.addWidget(self.radioButton_option2)
        self.radioButton_option3 = QtWidgets.QRadioButton(TakeQuizDialog)
        self.radioButton_option3.setObjectName("radioButton_option3")
        self.verticalLayout.addWidget(self.radioButton_option3)
        self.checkBox_option1 = QtWidgets.QCheckBox(TakeQuizDialog)
        self.checkBox_option1.setObjectName("checkBox_option1")
        self.verticalLayout.addWidget(self.checkBox_option1)
        self.checkBox_option2 = QtWidgets.QCheckBox(TakeQuizDialog)
        self.checkBox_option2.setObjectName("checkBox_option2")
        self.verticalLayout.addWidget(self.checkBox_option2)
        self.lineEdit_answer = QtWidgets.QLineEdit(TakeQuizDialog)
        self.lineEdit_answer.setObjectName("lineEdit_answer")
        self.verticalLayout.addWidget(self.lineEdit_answer)
        self.btn_next_question = QtWidgets.QPushButton(TakeQuizDialog)
        self.btn_next_question.setObjectName("btn_next_question")
        self.verticalLayout.addWidget(self.btn_next_question)
        self.btn_finish_quiz = QtWidgets.QPushButton(TakeQuizDialog)
        self.btn_finish_quiz.setObjectName("btn_finish_quiz")
        self.verticalLayout.addWidget(self.btn_finish_quiz)

        self.retranslateUi(TakeQuizDialog)
        QtCore.QMetaObject.connectSlotsByName(TakeQuizDialog)

    def retranslateUi(self, TakeQuizDialog):
        _translate = QtCore.QCoreApplication.translate
        TakeQuizDialog.setWindowTitle(_translate("TakeQuizDialog", "Take Quiz"))
        self.label_question.setText(_translate("TakeQuizDialog", "Question:"))
        self.radioButton_option1.setText(_translate("TakeQuizDialog", "Option 1"))
        self.radioButton_option2.setText(_translate("TakeQuizDialog", "Option 2"))
        self.radioButton_option3.setText(_translate("TakeQuizDialog", "Option 3"))
        self.checkBox_option1.setText(_translate("TakeQuizDialog", "Option 1"))
        self.checkBox_option2.setText(_translate("TakeQuizDialog", "Option 2"))
        self.btn_next_question.setText(_translate("TakeQuizDialog", "Next Question"))
        self.btn_finish_quiz.setText(_translate("TakeQuizDialog", "Finish Quiz"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TakeQuizDialog = QtWidgets.QDialog()
    ui = Ui_TakeQuizDialog()
    ui.setupUi(TakeQuizDialog)
    TakeQuizDialog.show()
    sys.exit(app.exec_())
